"""fixed warehouse and order tables - new columns for shipments

Revision ID: 7108ab52e607
Revises: f2a26a5751e0
Create Date: 2024-08-10 00:35:20.606039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7108ab52e607'
down_revision: Union[str, None] = 'f2a26a5751e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_line1', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(length=20), nullable=True))
    op.add_column('shipments', sa.Column('label_id', sa.String(length=100), nullable=True))
    op.add_column('shipments', sa.Column('label_download_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expiration')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('shipments', 'label_download_url')
    op.drop_column('shipments', 'label_id')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address_line1')
    op.drop_column('orders', 'shipping_name')
    # ### end Alembic commands ###
