"""orders ship date

Revision ID: 798a47a5a1f3
Revises: b3c43f10c6b6
Create Date: 2024-08-10 20:41:38.473210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798a47a5a1f3'
down_revision: Union[str, None] = 'b3c43f10c6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ship_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ship_date')
    # ### end Alembic commands ###
