"""yard tables

Revision ID: 9a2e0d99f12d
Revises: fc0f698a5c16
Create Date: 2024-08-08 17:38:21.169009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2e0d99f12d'
down_revision: Union[str, None] = 'fc0f698a5c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dock_appointments', sa.Column('actual_arrival_time', sa.DateTime(), nullable=True))
    op.add_column('dock_appointments', sa.Column('actual_departure_time', sa.DateTime(), nullable=True))
    op.add_column('yard_locations', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yard_locations', 'capacity')
    op.drop_column('dock_appointments', 'actual_departure_time')
    op.drop_column('dock_appointments', 'actual_arrival_time')
    # ### end Alembic commands ###
