"""inventory with expiration date

Revision ID: b3c43f10c6b6
Revises: 51ac04c186a2
Create Date: 2024-08-10 19:34:35.068712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c43f10c6b6'
down_revision: Union[str, None] = '51ac04c186a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('expiration_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'expiration_date')
    # ### end Alembic commands ###
