"""quality standard and alert

Revision ID: d82e8d3ece6f
Revises: bdc371f2e628
Create Date: 2024-08-08 15:11:23.325614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82e8d3ece6f'
down_revision: Union[str, None] = 'bdc371f2e628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_quality_alerts_alert_id'), 'quality_alerts', ['alert_id'], unique=False)
    op.create_table('quality_standards',
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('criteria', sa.String(length=100), nullable=False),
    sa.Column('acceptable_range', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('standard_id')
    )
    op.create_index(op.f('ix_quality_standards_standard_id'), 'quality_standards', ['standard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_standards_standard_id'), table_name='quality_standards')
    op.drop_table('quality_standards')
    op.drop_index(op.f('ix_quality_alerts_alert_id'), table_name='quality_alerts')
    op.drop_table('quality_alerts')
    # ### end Alembic commands ###
