"""rbac

Revision ID: e07fc64f054b
Revises: 9edb990b827a
Create Date: 2024-08-16 20:33:44.402171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07fc64f054b'
down_revision: Union[str, None] = '9edb990b827a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('can_read', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('can_write', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('can_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'can_delete')
    op.drop_column('permissions', 'can_write')
    op.drop_column('permissions', 'can_read')
    # ### end Alembic commands ###
